// ==== Login Related Constants ===== //
export const PLACING_DEVICES_INFORMATION = 'PLACING_DEVICES_INFORMATION';
export const DISPALYS_COMPONENT_INFORMATION = 'DISPALYS_COMPONENT_INFORMATION';
export const UPDATE_ITEMS_TO_DELETE = 'UPDATE_ITEMS_TO_DELETE';
